

replicaCount: 1

nameOverride: "frontend"
fullnameOverride: "frontend"

name: frontend

service:
  type: ClusterIP
  port: 80

frontend:
  image: <placeholder-image>
  pullPolicy: Always
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: devopshelper.eastus.cloudapp.azure.com
      paths: 
        - /
    - host: devopshelper.io
      paths: 
        - /
  tls:
   - secretName: tls-secret-prod
     hosts:
       - devopshelper.eastus.cloudapp.azure.com
       - devopshelper.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
